### ISSUE TITLE
context

### ISSUE THREAD

**Issue by bketelsen** [servemux/context#1]
context as a map isn't idiomatic, net/context is.  Please consider changing this lib to use net/context instead.

**Comment by hallas** [comment]
Yup. Already working on a near solution. Maybe you can review a PR later?

**Comment by hallas** [comment]
New*

**Comment by bketelsen** [comment]
Happy to, but I'll be out of country for the next few days.  just @ mention me and I'll get to it when I can.

**Comment by hallas** [comment]
Sweet. I'm thinking about keeping the map for states and then adding a background context into this handler with a convenience function that lets you create a new context with a value from the map. It could make sense when written in code. I'll mention. 

Thanks!

**Comment by hallas** [comment]
@bketelsen I really wanted to get this in so I just added it how I think it makes sense into master. Please have a look now and make sure to see the example as well.

We can do PRs for improvement from now on?
